spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_management_system?createDatabaseIfNotExist=true
    username: root
    password: Phantom080802
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-master.yml